name: build
on: [push, pull_request, workflow_dispatch]
jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - run: python -m pip install --upgrade pip wheel ruff
      - run: ruff check .

  tests:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - run: python -m pip install --upgrade pip wheel
      - run: python -m pip install pytest pytest-cov pytest-asyncio pytest-timeout
      - run: python -m pip install simple-websocket uvicorn requests websocket-client aiohttp msgpack
      - run: python -m pip install -e .
      - run: pytest tests -p no:logging --timeout=60 --cov=fastsio --cov-branch


  coverage:
    name: coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - run: python -m pip install --upgrade pip wheel
      - run: pip install tox tox-gh-actions
      - run: tox
      - uses: codecov/codecov-action@v3
        with:
          files: ./coverage.xml
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
